fix hrefs values
eoscostarica/lifebank pull request #226
Opened 2020-09-04 20:45 UTC by JustinCast

# Fix incorrect href values
Change hrefs values from jungle.bloks.io to jungle3.bloks.io

## How this should be tested
- Type `make run` in the terminal
- Go to `localhost:3000` and see the magic﻿

2020-09-04 21:01 UTC, xavier506 commented on webapp/src/components/MapPopup/index.js
> +          href={`https://jungle3.bloks.io/account/${account}`}
Should we set this as an env var?

2020-09-04 21:10 UTC, xavier506 approved these changes

2020-09-04 23:42 UTC, JustinCast commented on webapp/src/components/MapPopup/index.js
> +          href={`https://jungle3.bloks.io/account/${account}`}
Fixed in the last commit!.

2020-09-05 01:50 UTC, xavier506 approved these changes
LGTM

2020-09-07 18:55 UTC, JeanVegaD approved these changes

2020-09-07 19:00 UTC, adriexnet requested changes

2020-09-07 19:00 UTC, adriexnet commented on webapp/src/components/RicardianContract/RicardianContract.js
> +    const nameSection = `**Name:** [${name}](${process.env.REACT_APP_BLOCK_EXPLORER_URL}account/${name}?loadContract=true&tab=Actions)`
Same issue here, please use src/config and then import the variable from there

2020-09-08 16:30 UTC, adriexnet approved these changes
LGTM

2020-09-08 16:58 UTC, merged