update maps component
eoscostarica/lifebank pull request #228
Opened 2020-09-07 23:05 UTC by JeanVegaD

# What does this PR do?

#204 
- create a new component for display a single lifebank or sponsor
- create a component to edit the location of lifebank or sponsor
- create a component to display a static map
- update the map display in modal format
- create filters to search for  lifebanks and sponsors 

# How this should be tested?

- make run
- go to http://localhost:3000

2020-09-08 20:39 UTC, JustinCast requested changes

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapEditLocation/index.js
> +
Maybe can remove this unnecessary blank space

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapEditLocation/index.js
> +  var markerNode = null
Le'ts use **let** or **const** instead of var

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapModal/MapModal.js
> +// import LifeBankSvg from './LocatorDonators.js'
Do we need this comments?

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapShowOneLocation/index.js
> +
Maybe we could remove this unnecessary blank space

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapStatic/index.js
> +
Maybe we could delete this unnecessary blank space

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapStatic/index.js
> +    var heightMap = windowSize / 2
Please use **let** or **const** instead of var

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapStatic/index.js
> +    var api = "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-84.0556371,9.9195872,7/" + windowSize.toString() + "x" + heightMap.toString() + "?access_token=" + mapboxConfig.accessToken
Same here

2020-09-08 20:39 UTC, JustinCast commented on webapp/src/components/MapStatic/index.js
> +        aria-labelledby="transition-modal-title"
What if we add some useful description?

2020-09-09 15:20 UTC, JustinCast requested changes

2020-09-09 15:20 UTC, JustinCast commented on webapp/src/components/MapShowOneLocation/index.js
> +var searchDistance = 5000
We can use let instead of var

2020-09-09 15:20 UTC, JustinCast commented on webapp/src/routes/Profile/ProfilePageLifebank.js
> +      { /* Edit location
Do we need this comment?

2020-09-11 17:02 UTC, xavier506 approved these changes
LGTM

2020-09-12 03:33 UTC, tetogomez reviewed
Please check the comments

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +var map = null
remove all var declarations and use const or let if you need change the value!

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +    if (event.target.name === "checkedLifebank") {
add blank space after the `setState`

Also we can do better that logic removing the IF STATEMENT and using SWITCH, if you want to switch the boolean values try to do something like that:
```
switch(name) {
  case 'checkedLifebank': {
    checkLifebank = !checkLifebank
    
    break
  }
    
  default: {
  checkSponsor = !checkSponsor
    
    break
  }
}
```

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +
delete blank space

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +        const markerNode = document.createElement('div')
add blank space after const declaration

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +        const popupNode = document.createElement('div')
same here!

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +        var markertemp = new mapboxgl.Marker(markerNode)
avoid to use var, you can use const or let if you need to modified the variable value

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +    var matchingFeatures = [];
same here!

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +      var feature = customData.features[i];
and here

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +        feature.center = feature.geometry.coordinates;
add blank space here (remember before if statement declaration add a blank space)

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowLocations/index.js
> +              <Grid item xs={12}><TextField label="Offer categories" variant="outlined" className={classes.inputStyle} /></Grid>
delete that commented code

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowOneLocation/index.js
> +
delete blank space

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowOneLocation/index.js
> +        const markerNode = document.createElement('div')
add blank space after const declaration

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowOneLocation/index.js
> +        const popupNode = document.createElement('div')
same here

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapShowOneLocation/index.js
> +          var markertemp = new mapboxgl.Marker(markerNode)
avoid use `var`

2020-09-12 03:33 UTC, tetogomez commented on webapp/src/components/MapStatic/index.js
> +    if (windowSize > 1280) {
add blank space before and after if statement declaration

2020-09-15 21:10 UTC, tetogomez approved these changes
LGTM

2020-09-15 21:37 UTC, merged