functionality:add new fields to edit lifebank profile
eoscostarica/lifebank pull request #230
Opened 2020-09-09 18:38 UTC by AngeloCG97

## Lifebank info pages 

#186 

### What does this PR contain?
- add new fields to section edit profile lifebank
- add function to load schedule to edit the profile of a lifebank

### How this should be tested?
- make run
- go to http://localhost:3000

2020-09-09 19:05 UTC, JustinCast requested changes

2020-09-09 19:05 UTC, JustinCast commented on hapi/src/api/account.api.js
> +const LIFEBANKCODE_CONTRACT = 'lifebankcode' // @todo: use ENV
Take a look at codefactor warning

2020-09-09 19:05 UTC, JustinCast commented on webapp/src/components/Schedule/Schedule.js
> +        onClose={() => { }}
What about this empty handling?

2020-09-09 19:05 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfileBank.js
>      description: profile.description,
Take a look at codefactor's warnings

2020-09-09 20:02 UTC, JustinCast approved these changes

2020-09-11 17:01 UTC, xavier506 approved these changes
LGTM

2020-09-12 02:59 UTC, tetogomez approved these changes
LGTM

2020-09-12 03:29 UTC, merged