feat: offer pages
eoscostarica/lifebank pull request #242
Opened 2020-09-18 16:28 UTC by JeanVegaD

# What does this PR do?

#188 

- create a page when the donor can see the sponsors' offers
- create filters for offers searches
- create a page when the donor can see a specific offer

# How this should be tested?

- make run
- go to http://localhost:3000
- login as donor
- go to available offers section

2020-09-18 20:02 UTC, JustinCast requested changes

2020-09-18 20:02 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +  const [offer, setOffer] = React.useState(
@JeanVegaD please import useState from 'react' instead of using React.useState

2020-09-18 20:02 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +  const [loading, setLoading] = React.useState(true);
same here

2020-09-18 20:02 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +  const [isOffer, setIsOffer] = React.useState(false);
Same here

2020-09-18 20:02 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +      <Fragment>
Why two fragments here?

2020-09-21 14:53 UTC, JustinCast requested changes

2020-09-21 14:53 UTC, JustinCast commented on webapp/src/routes/Offers/Offers.js
> +      <Fragment>
Please use Fragment shorthand <> </>

2020-09-21 14:53 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +  const [offer, setOffer] = useState(
Seems like you forgot to import useState hook from 'react'

2020-09-21 14:53 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +  const classes = useStyles()
Same here

2020-09-21 14:53 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +  const [loading, setLoading] = useState(true);
Same here

2020-09-21 14:53 UTC, JustinCast commented on webapp/src/routes/OfferPage/OfferPage.js
> +    <Fragment>
Please use Fragment shorthand <> </>

2020-09-25 12:41 UTC, xavier506 approved these changes

2020-09-25 12:41 UTC, merged