Function (Pre register lifebank): add new function to pre register lifebank  to lifebank role flow
eoscostarica/lifebank pull request #244
Opened 2020-09-21 22:48 UTC by AngeloCG97

## Lifebank on-boarding flow

#215 

### What does this PR do?
- Create actions and mutatios to the pre register.
- Create Hapi files to the pre register.
- Create verification code generator
- Modify SiginLifebank page. 

### How should this be tested?
- Run make run
- go to localhost:3000

2020-09-21 22:55 UTC, JustinCast requested changes

2020-09-21 22:55 UTC, JustinCast commented on hapi/src/api/lifebank.api.js
> +    console.error(error);
Take a look at this semicolon

2020-09-21 22:55 UTC, JustinCast commented on hapi/src/api/lifebank.api.js
> +  resultRegister = "ok"
Please take a look at codefactor's suggestions

2020-09-21 22:55 UTC, JustinCast commented on hapi/src/api/pre-register.api.js
> +  return hasuraUtils.request(INSERT, { preregister_lifebank })
Take a look at this

2020-09-21 22:55 UTC, JustinCast commented on webapp/src/gql/pre-register-lifebank.gql.js
> +  mutation($email: String!, $password: String!, $name: String!, $address: String!, $schedule: String!, $phone: String!, $description: String!, $urgency_level: Int!, $coordinates: String!, $immunity_t
Please organize the code in line divisions instead of just using one line

2020-09-21 22:55 UTC, JustinCast commented on hapi/src/routes/pre-register/pre-register-lifebank.handler.js
> +
Maybe we can remove this blank space

2020-09-22 15:09 UTC, JustinCast approved these changes

2020-09-23 10:52 UTC, xavier506 approved these changes

2020-09-23 19:29 UTC, JeanVegaD approved these changes

2020-09-23 21:05 UTC, JustinCast approved these changes

2020-09-24 00:18 UTC, murillojorge requested changes
There seems to be a syntax error in Schedule.js. Please take a look.

2020-09-25 17:50 UTC, merged