Donor on boarding flow
eoscostarica/lifebank pull request #248
Opened 2020-09-28 21:32 UTC by JeanVegaD

# What does this PR do?

#219 

- update login and signup with email
- add authentication with Facebook and Google 

# How this should be tested?

- make run
- go to http://localhost:3000
- try to login/signup with email, Facebook, or Google

2020-09-29 01:28 UTC, JustinCast requested changes

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/components/LoginModal/LoginWithFacebook.js
> +  const responseFacebook = (response) => {
`facebookResponse` ?

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/components/LoginModal/LoginWithFacebook.js
> +
remove the blank space and make the validation in one single line

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/components/LoginModal/LoginWithFacebook.js
> +      <FacebookProvider appId="641671940102186">
What about if we load this from a config file?

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/gql/account.gql.js
> +    create_account(role: $role, email: $email, name:$name, secret: $secret) {
add white `space name:$name` to `name: $name`

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/routes/Signup/ValidateEmail.js
> +            ? ''
Please avoid using complex validations

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/routes/Signup/socialSingup/SignupWithFacebook.js
> +      handlerSubmit(false, "", "", "")
Make the validation in one single line

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/routes/Signup/socialSingup/SignupWithFacebook.js
> +      <FacebookProvider appId="641671940102186">
Maybe is better to load this from a config file

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/routes/Signup/socialSingup/SignupWithGoogle.js
> +    if (error) {
Make the validation in one single line

2020-09-29 01:28 UTC, JustinCast commented on webapp/src/routes/Signup/socialSingup/SignupWithGoogle.js
> +      clientId="865299157499-ht14599cb2vaqgnq0vhkihsedsfvcukf.apps.googleusercontent.com"
Maybe is better to load this from a config file

2020-09-29 15:33 UTC, JustinCast requested changes

2020-09-29 15:33 UTC, JustinCast commented on webapp/src/components/LoginModal/LoginWithFacebook.js
> +    if (error) { onSubmit(false, "", "") }
When the validation has only one line in its body, you can remove curly braces. So, the result is `if (error) onSubmit(false, "", "")`

2020-09-29 15:33 UTC, JustinCast commented on webapp/src/components/LoginModal/LoginWithGoogle.js
> +    if (error) { onSubmit(false, "", "") }
unnecessary curly braces here

2020-09-29 16:30 UTC, JustinCast approved these changes

2020-09-30 14:12 UTC, JustinCast approved these changes

2020-10-01 15:46 UTC, tetogomez reviewed
Please check the comments

2020-10-01 15:46 UTC, tetogomez commented on webapp/src/components/LoginModal/LoginWithFacebook.js
> +    <>
este `fragment` es necesario ?

2020-10-01 15:46 UTC, tetogomez commented on webapp/src/routes/Signup/socialSingup/SignupWithFacebook.js
> +    <>
same here

2020-10-01 16:09 UTC, murillojorge requested changes
Please review unique ids on user table.

 FatalError: there is no unique constraint matching given keys for referenced table \"user\""

2020-10-03 01:58 UTC, xavier506 commented on package.json
> +  "dependencies": {}
@JeanVegaD  do we need this file?

2020-10-05 14:35 UTC, JustinCast requested changes

2020-10-05 14:35 UTC, JustinCast commented on webapp/src/routes/Signup/Signup.js
> +      } else {
Unnecessary curly braces here

2020-10-05 14:35 UTC, JustinCast commented on webapp/src/routes/Signup/Signup.js
> +          if (!err) {
Unnecessary curly braces here

2020-10-06 15:55 UTC, AngeloCG97 approved these changes

2020-10-06 16:21 UTC, JustinCast approved these changes

2020-10-06 16:22 UTC, merged