Add process to send email verification
eoscostarica/lifebank pull request #249
Opened 2020-09-28 22:46 UTC by AngeloCG97

## Lifebank on-boarding flow
#215

### What does this PR do?

- Create html to email verification.
- Create a new table to management code verification.
- Edit pregister lifebank, add new column "email_verified" and delete column verificarion_code
- Modify process to valide email, delete duplicate funtion.

### How should this be tested?
- Run make run
- go to localhost:3000

2020-09-29 01:21 UTC, JustinCast requested changes
Please check your spelling

2020-09-29 01:21 UTC, JustinCast commented on hapi/src/api/pre-register.api.js
> +const INSERTVERIFICATEEMAIL = `
Ops, we need to correct this typo

2020-09-29 01:21 UTC, JustinCast commented on hapi/src/api/pre-register.api.js
> +  mutation ($verificate_email: verificate_email_insert_input!) {
`verification_email` ?

2020-09-29 01:21 UTC, JustinCast commented on hapi/src/api/pre-register.api.js
> +  mutation ($verificate_email: verificate_email_insert_input!) {
`verificate_email_insert_input` ?

2020-09-29 01:21 UTC, JustinCast commented on hapi/src/api/pre-register.api.js
> +  return hasuraUtils.request(INSERTLIFEBANK, { preregister_lifebank })
Check these typos, please

2020-09-29 16:29 UTC, JustinCast approved these changes

2020-09-30 03:22 UTC, xavier506 approved these changes
@AngeloCG97  please see code fctor comment

2020-10-01 02:29 UTC, merged