Pre register lifebank
eoscostarica/lifebank pull request #255
Opened 2020-10-02 18:16 UTC by AngeloCG97

#215 

# What does this PR do?

- Delete table verification email.
  - Modify tables:
  - Add verification_code colum in user and preregister_lifebank

# How this should be tested?

- make run
- go to http://localhost:3000
- register lifebank

2020-10-02 20:32 UTC, JustinCast requested changes

2020-10-02 20:32 UTC, JustinCast commented on hapi/src/api/account.api.js
> +  let verification_code = await verificationCodeApi.generate()
please use const { verificationCode]

2020-10-02 21:55 UTC, AngeloCG97 commented on hapi/src/api/account.api.js
> +  let verification_code = await verificationCodeApi.generate()
ready this change

2020-10-05 14:23 UTC, JustinCast approved these changes

2020-10-06 05:34 UTC, xavier506 approved these changes

2020-10-06 05:34 UTC, merged