Front end redesign
eoscostarica/lifebank pull request #275
Opened 2020-10-14 21:25 UTC by JeanVegaD

2020-10-14 22:47 UTC, JustinCast requested changes

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowSponsors.js
> +
Remove the whitespace here

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowSponsors.js
> +
Please remove this whitespace

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowSponsors.js
> +    if (str.length <= num) {
If the conditional has only one line in its body, you can remove the brackets

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowSponsors.js
> +
Please remote this white space

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowSponsors.js
> +
Please remove this whitespace

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowOffers.js
> +
Please remove this whitespaces

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowOffers.js
> +
Remove this whitespaces

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowOffers.js
> +    return (
please remove this white space

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowOffers.js
> +    return (
When the components only has a return in its JSX content, you can do something like
```
const OfferItem = (props) => (
    JSX HERE
)
```

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowOffers.js
> +  const LoadOffers = () => {
When the components only has a return in its JSX content, you can do something like

```
const OfferItem = (props) => (
    JSX HERE
)
```

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowOffers.js
> +
Please remove this whitespace

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +
Please remove this whitespace

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +  const BankCard = (props) => {
When the components only has a return in its JSX content, you can do something like

```
const OfferItem = (props) => (
    JSX HERE
)
```

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +
Please remove this whitespace

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +    if (str.length <= num) {
Unnecessary curly braces here

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +  const LoadBanksDesktop = () => {
When the components only has a return in its JSX content, you can do something like

```
const OfferItem = (props) => (
    JSX HERE
)
```

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +
Please remove this whitespace

2020-10-14 22:47 UTC, JustinCast commented on webapp/src/components/Notification/Notification.js
> +
Please remove this whitespace here

2020-10-15 15:05 UTC, JustinCast approved these changes

2020-10-15 15:23 UTC, AngeloCG97 approved these changes

2020-10-15 15:23 UTC, merged