Fix the error when you go to the life bank information page outside the website
eoscostarica/lifebank pull request #298
Opened 2020-10-21 18:21 UTC by AngeloCG97

## Fix bug to open lifebank info page to the browse 

closes #284 

### What does this PR do?
- Create FK in location table whit user table.
- Change get URL direction
- Create query to get profile lifebank and modify other querry
- Modify MapPopup component

### How should this be tested?
- Run make run
- Go to localhost:3000
- Go to lifebank info page

2020-10-21 20:35 UTC, JeanVegaD requested changes
- fix Hasura migrations problem
- fix URL in the desktop version
- add not-found page when URL doesn't match

2020-10-21 20:40 UTC, JustinCast requested changes

2020-10-21 20:40 UTC, JustinCast commented on webapp/src/gql/account.gql.js
Remove this unnecessary white space please

2020-10-21 20:40 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
>    const BankItem = (props) => {
You can use parenthesis when in the JSX Element body is just a return

2020-10-21 20:40 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +
Remove this white space please

2020-10-22 15:08 UTC, JustinCast requested changes

2020-10-22 15:08 UTC, JustinCast commented on webapp/src/routes/InfoPage/InfoPage.js
> +    if (location.state) {
Remove these unnecessary curly braces

2020-10-22 15:08 UTC, JustinCast commented on webapp/src/routes/InfoPage/InfoPage.js
> +          setProfile(data.location[0])
Use a ternary operator or remove the unnecessary curly braces

2020-10-22 15:09 UTC, JustinCast commented
![image](https://user-images.githubusercontent.com/17890146/96891818-43a3b300-1446-11eb-8f84-172d92f94584.png)
There is a conflict here

2020-10-22 17:25 UTC, tetogomez commented on webapp/src/routes/Home/ShowLifebanks.js
> +        pathname: 'info/' + props.bank.user.username.replaceAll(" ", "-"),
We can change this string concat (old school XD) and use template string.

example:
```
pathname: `info/${props.bank.user.username.replaceAll(" ", "-")}`
```

2020-10-22 17:25 UTC, tetogomez commented on webapp/src/routes/Home/ShowLifebanks.js
> +          pathname: 'info/' + props.bank.user.username.replaceAll(" ", "-"),
same here, use template string

2020-10-23 20:46 UTC, JustinCast requested changes

2020-10-23 20:46 UTC, JustinCast commented on webapp/debug.log
> +[1014/085359.567:ERROR:directory_reader_win.cc(43)] FindFirstFile: El sistema no puede encontrar la ruta especificada. (0x3)
What is this file @AngeloCG97 ?

2020-10-23 20:46 UTC, JustinCast commented on webapp/src/components/MapPopup/index.js
> +      return "https://maps.google.com/maps?q=" + info.geolocation.latitude + "," + info.geolocation.longitude
use template string please

2020-10-23 21:36 UTC, JustinCast approved these changes

2020-10-23 21:46 UTC, JeanVegaD approved these changes

2020-10-23 21:53 UTC, merged