feat: offer view
eoscostarica/lifebank pull request #324
Opened 2020-10-27 15:18 UTC by JeanVegaD

# What does this PR do?
#272 
- create a new offer view design 

# How this should be tested?
- go to http://localhost:3000
- open an offer

2020-10-28 15:13 UTC, AngeloCG97 approved these changes

2020-10-28 16:28 UTC, JustinCast requested changes

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +  const fullScreen = useMediaQuery(theme.breakpoints.down('sm'));
Remove this semicolon

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +  const theme = useTheme();
Unnecessary semicolon here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +  };
Unnecessary semicolon here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +    setOpen(false);
Unnecessary semicolon here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +          <DialogTitle id="responsive-dialog-title" className={classes.title}>Sponsor Location</DialogTitle>
Add the translations please

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +
Remove this whitespace please

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +const monthKey = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Agt", "Sep", "Oct", "Nov", "Dec"]
Add the translations please

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +});
Unnecessary semicolon here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +  };
Unnecessary semicolon here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +    setActiveStep((prevActiveStep) => prevActiveStep - 1);
Unnecessary semicolon here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +  const ShowImages = () => {
Remember that you can omit return word when in a JSX body are no more elements

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +  const OfferContent = () => {
You can omit the return here

2020-10-28 16:28 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +};
Unnecessary semicolon here

2020-10-28 19:04 UTC, JustinCast requested changes

2020-10-28 19:04 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +  };
Unnecessary semicolon here

2020-10-28 19:04 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +
Unnecessary blank space here

2020-10-28 19:04 UTC, JustinCast commented on webapp/src/components/MapModalOneLocation/MapModalOneLocation.js
> +          LOCATION
I saw you imported useTranslation. Maybe we can translate this

2020-10-28 19:26 UTC, JustinCast requested changes

2020-10-28 19:26 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +];
I think you forgot to remove the unnecessary semicolons

2020-10-28 19:26 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +});
Semicolons here. Please remove them, since they are not necessary in standard js

2020-10-28 19:26 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +  };
Unnecessary semicolons here

2020-10-28 19:26 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +  };
Unnecessary semicolons here

2020-10-28 19:26 UTC, JustinCast commented on webapp/src/components/DonationsDashboard/DonationsDashboard.js
> +  const [maxWidth] = useState('md');
Please remove the unnecessary semicolon here

2020-10-28 19:26 UTC, JustinCast commented on webapp/src/components/DonationsDashboard/DonationsDashboard.js
> +};
Unnecessary semicolon here

2020-10-29 01:27 UTC, tetogomez reviewed
LGTM, just see Justin's comments

2020-10-29 21:23 UTC, JustinCast requested changes

2020-10-29 21:23 UTC, JustinCast commented on webapp/src/components/OfferView/OfferView.js
> +        <Dialog open={openOfferView} onClose={handleCloseOfferView} TransitionComponent={Transition} maxWidth={"sm"} fullWidth>
Unnecessary curly braces here. maxWidth={"sm"} could be maxWidth="sm"

2020-10-29 22:55 UTC, xavier506 commented on webapp/src/language/en.json
> +      "favourite": "Favourite",
Lets use the american spelling : " favorite"

2020-10-30 16:25 UTC, JustinCast approved these changes

2020-10-30 16:26 UTC, merged