Conset section
eoscostarica/lifebank pull request #360
Opened 2020-11-10 17:02 UTC by JeanVegaD

2020-11-10 21:46 UTC, AngeloCG97 approved these changes

2020-11-11 14:44 UTC, JustinCast requested changes

2020-11-11 14:44 UTC, JustinCast commented on webapp/src/components/ConsetComponent/ConsentComponent.js
> +    if (currentUser) {
Unnecessary curly braces here

2020-11-11 14:44 UTC, JustinCast commented on webapp/src/components/ConsetComponent/ConsentComponent.js
> +ConsetComponent.propTypes = {
Empty proptypes. Maybe we can remove it

2020-11-11 14:44 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +
Extra white spaces here

2020-11-11 19:49 UTC, JustinCast approved these changes

2020-11-11 19:50 UTC, merged