Seed data
eoscostarica/lifebank pull request #362
Opened 2020-11-10 20:22 UTC by JustinCast

# Seed Insomnia functionality
This PR provides the functionality to initially seed the DB
# How this should be tested?
- Download [Insomnia](https://insomnia.rest/) 
- Import Insomnia data present in seed directory
- Run the request sequentially
![image](https://user-images.githubusercontent.com/17890146/98729123-0dc85f00-2360-11eb-9163-1760fa849953.png)

# Note
You need to have lifebankcode local wallet created (with its respective lifebankcode keys)
## Linked issues
closes #357

2020-11-10 21:18 UTC, AngeloCG97 requested changes

2020-11-10 21:18 UTC, AngeloCG97 commented on webapp/src/routes/Profile/ProfilePageSponsor.js
> +  console.log(profile)
review console.log

2020-11-10 21:20 UTC, JustinCast commented on webapp/src/routes/Profile/ProfilePageSponsor.js
> +  console.log(profile)
fixed

2020-11-16 19:59 UTC, AngeloCG97 approved these changes

2020-11-17 19:35 UTC, JeanVegaD approved these changes

2020-11-18 15:17 UTC, merged