Fix/update sponsor profile bug
eoscostarica/lifebank pull request #372
Opened 2020-11-16 16:49 UTC by JustinCast

# Fix Sponsor's complete profile functionality
This PR provides a fix for an unexpected behavior when completing the sponsor profile
# How this should be tested?
- `make run`
- Go to `localhost:3000`
- Create a new sponsor
- Go and complete the fields
- Save the changes
# Linked issues
closes #366

2020-11-16 19:53 UTC, AngeloCG97 commented on webapp/src/routes/EditProfile/EditProfileSponsor.js
> +//import Logo from '../../components/Logo'
review this comment

2020-11-16 22:18 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfileSponsor.js
> +//import Logo from '../../components/Logo'
Fixed it!

2020-11-20 15:47 UTC, JeanVegaD requested changes
edit profile doesn't allow update location

2020-11-20 16:57 UTC, JeanVegaD approved these changes

2020-11-20 17:33 UTC, AngeloCG97 approved these changes

2020-11-20 17:33 UTC, merged