Manage token
eoscostarica/lifebank pull request #386
Opened 2020-11-18 23:57 UTC by AngeloCG97

## Manage token expiration 

#367

### What does this PR do?
- Extended time to expired token basic
- When token expired logout user

### How should this be tested?
- Run make run
- Go to localhost:3000
- Change time to expire token in 30 in the file jw.js in line 20 for fast a prove expiration token

2020-11-19 16:36 UTC, JustinCast commented on hapi/src/utils/jwt.js
> +  jwt.setExpiration(new Date().getTime() + 30)
Why 30?

2020-11-19 16:40 UTC, JustinCast requested changes

2020-11-19 16:40 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +    if (getAllOffersError) {
Unnecessary curly braces here

2020-11-19 16:40 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +      if (valueOfferCat !== 'All') {
Unnecessary curly braces here

2020-11-19 16:40 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +      if (valueSponsorCat !== 'All') {
Unnecessary curly braces here

2020-11-19 16:40 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +      if (valueTokenPrice !== 'All') {
Unnecessary curly braces here

2020-11-19 16:40 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +      if (searchValue !== "") {
Unnecessary curly braces here

2020-11-19 16:40 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +      if (valueSponsorCat !== 'All') {
Unnecessary curly braces here

2020-11-19 23:07 UTC, JeanVegaD approved these changes

2020-11-20 00:51 UTC, JustinCast requested changes
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/17890146/99742027-3525d700-2a98-11eb-8098-6f933a781d2a.png">
Take a look at this

2020-11-20 00:53 UTC, JustinCast commented
> <img alt="image" width="1160" src="https://user-images.githubusercontent.com/17890146/99742027-3525d700-2a98-11eb-8098-6f933a781d2a.png">
> 
> Take a look at this

This happen when you logout, being in the profile

2020-11-20 15:05 UTC, JustinCast approved these changes

2020-11-20 15:05 UTC, merged