feat: error pages
eoscostarica/lifebank pull request #391
Opened 2020-11-23 14:55 UTC by JeanVegaD

2020-11-26 14:55 UTC, JustinCast requested changes

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/LoginModal/Login.js
> +          } else {
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/MapShowLocations/index.js
> +          <MapPopup id={id} info={info} username = {user.username.replaceAll(' ','-')} account={account} />,
Delete spaces between '=' symbol

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/MapShowOneLocation/index.js
> +          <MapPopup id={id} info={info} username = {user.username.replaceAll(' ','-')} account={account} />,
Delete spaces between '=' symbol

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/Signup/Signup.js
> +    }
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/ConsetComponent/ConsentComponent.js
>    ] = useLazyQuery(PROFILE_QUERY, { fetchPolicy: 'network-only' })
Take a loot at this warning

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/DonationsDashboard/DonationsDashboard.js
> +  }
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/components/Signup/Signup.js
> +    }
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfile.js
> +      }
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/EmailVerification/EmailVerification.js
>  import Button from '@material-ui/core/Button'
Take a look at this warning

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/EmailVerification/EmailVerification.js
> +  tittle: {
seems there is a typo here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/EmailVerification/EmailVerification.js
> +    fontFamily: "Roboto",
Roboto Font is now preloaded. So, it's not necessary to specify Roboto in the css styles

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/Home/Home.js
> +  }
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/InternalError/InternalError.js
> +    fontFamily: "Roboto",
It's not necessary to use Roboto in this way

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/Profile/ProfilePage.js
> +      } else {
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/Profile/ProfilePageLifebank.js
>      variables: {
Take a loot at this warning

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/Profile/ProfilePageLifebank.js
> +      } else {
Unnecessary curly braces here

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/RegisterLifebank/RegisterLifebank.js
>  import CircularProgress from '@material-ui/core/CircularProgress'
Take a look at this warning

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/RegisterLifebank/RegisterLifebank.js
> +import { useUser } from '../../context/user.context'
Take a look at this warning

2020-11-26 14:55 UTC, JustinCast commented on webapp/src/routes/RegisterLifebank/RegisterLifebank.js
> +    fontFamily: "Roboto",
It's not necessary to specify Roboto in this way. The font is now pre-loaded

2020-12-01 19:18 UTC, JustinCast commented
Seems there are some conflicts @JeanVegaD

2020-12-01 19:38 UTC, AngeloCG97 commented
re-view codefactor warnings

2020-12-01 19:50 UTC, JustinCast requested changes

2020-12-01 19:50 UTC, JustinCast commented on webapp/src/App.js
>    const [validSponsors, setValidSponsors] = useState([])
Seems there are some codefactor suggestions here

2020-12-01 19:55 UTC, JustinCast requested changes

2020-12-01 19:55 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +            src={`//images.weserv.nl?url=${props.bank.logo || ''
In this case, it is better to maintain the validation to avoid something like //images.weserv.nl?url=''&h=60&dpr=1

2020-12-01 19:55 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +            }&h=300&dpr=2`}
Same situation with images here

2020-12-01 19:55 UTC, JustinCast commented on webapp/src/routes/Home/ShowSponsors.js
> +          src={`//images.weserv.nl?url=${props.sponsor.logo || ''
Same situation with images here

2020-12-01 19:56 UTC, JustinCast commented on webapp/src/routes/Home/ShowLifebanks.js
> +            src={`//images.weserv.nl?url=${props.bank.logo || ''
So, if the image is null or '', we wouldn't need to render or use src

2020-12-01 20:01 UTC, AngeloCG97 approved these changes

2020-12-01 20:02 UTC, JustinCast approved these changes

2020-12-01 20:02 UTC, merged