Mapbox tooltip
eoscostarica/lifebank pull request #412
Opened 2020-12-02 21:53 UTC by AngeloCG97

## Mapbox tooltip

#380 

### What does this PR do?

- Change desing MapPopUp component
- Add open and close now element

### How should this be tested?

- Run make run
- Go to localhost:3000
- Go to map section and selected lifebank or sponsor icon

2020-12-02 22:13 UTC, JustinCast commented
Did you forget to add **_closes_** word?

2020-12-02 22:14 UTC, JustinCast requested changes

2020-12-02 22:14 UTC, JustinCast commented on webapp/src/components/MapPopup/index.js
> +        if (dd === element.day) {
Unnecessary curly braces here

2020-12-02 22:31 UTC, JustinCast approved these changes

2020-12-03 15:19 UTC, JeanVegaD requested changes
check this
![image](https://user-images.githubusercontent.com/19317138/101048904-a362a300-3548-11eb-9c9b-ddc9e148c104.png)

2020-12-04 17:26 UTC, JeanVegaD approved these changes

2020-12-04 17:26 UTC, merged