Broke logout in profile section
eoscostarica/lifebank pull request #429
Opened 2020-12-07 17:23 UTC by AngeloCG97

## Broke logout in profile section

closes #290 

### What does this PR do?
- Fix bug to logout in profile section
- Change stile to add button in schedule component

### How should this be tested?

- Run make run
- Go to localhost:3000
- Go to profile page and logout in this section.
- Go to schedule component and view add button.

2020-12-07 17:34 UTC, JustinCast approved these changes

2020-12-08 16:50 UTC, JustinCast commented
@AngeloCG97 take a look at this conflict

2020-12-08 16:51 UTC, JustinCast requested changes
Take a look at the conflicts

2020-12-08 20:23 UTC, JeanVegaD approved these changes

2020-12-08 20:40 UTC, merged