Apply lowercase, and delete spaces #434
eoscostarica/lifebank pull request #435
Opened 2020-12-07 23:23 UTC by AngeloCG97

## Apply lowercase, and delete spaces

closes #434

### What does this PR do?
- Apply lowercase, and delete spaces in this secctions
  - Login
  - Credential recovery
  - Donations dashboard

### How should this be tested?

- Run make run
- Go to localhost:3000
- Go to login, credential recovery and donations dashboard

2020-12-08 14:43 UTC, JustinCast approved these changes

2020-12-08 20:23 UTC, JeanVegaD approved these changes

2020-12-08 20:42 UTC, JustinCast commented
@AngeloCG97 take a look at this conflict

2020-12-08 20:42 UTC, JustinCast requested changes
Take a look at the conflict

2020-12-09 02:12 UTC, JustinCast approved these changes

2020-12-09 02:13 UTC, merged