fix: MapPopup render problem
eoscostarica/lifebank pull request #451
Opened 2020-12-09 20:05 UTC by JustinCast

# Fix MapPopup render problem
This PR provides a fix for the render problem when calling the component
# How does this should be tested?
- `make run`
- Login as sponsor or lifebank and go to the profile section
- Check if there is anything unusual

2020-12-09 20:48 UTC, AngeloCG97 requested changes

2020-12-09 20:48 UTC, AngeloCG97 commented on webapp/src/components/MapShowOneLocation/index.js
> +            username={user.username}
in this line a replace all necessary was eliminated

2020-12-10 14:54 UTC, JeanVegaD commented
there seem to be layout issues with the popup

![image](https://user-images.githubusercontent.com/19317138/101787914-3bbad380-3ac5-11eb-88f6-427ad1aac02e.png)

2020-12-10 14:54 UTC, JeanVegaD commented
check code factor suggestions

2020-12-10 14:56 UTC, JustinCast commented
> there seem to be layout issues with the popup
> 
> ![image](https://user-images.githubusercontent.com/19317138/101787914-3bbad380-3ac5-11eb-88f6-427ad1aac02e.png)

That is more concerning with the design than with the fix itself

2020-12-11 15:00 UTC, AngeloCG97 requested changes
Design is broke

![image](https://user-images.githubusercontent.com/51149817/101918675-404bbe80-3b8f-11eb-9fda-55610c38fafd.png)

2020-12-14 14:46 UTC, AngeloCG97 requested changes

2020-12-14 14:46 UTC, AngeloCG97 commented on hapi/src/api/account.api.js
> +  // } catch (error) {
delete comments before to push

2020-12-14 14:50 UTC, JeanVegaD requested changes
I think it looks very small

![image](https://user-images.githubusercontent.com/19317138/102095650-61a7e700-3de9-11eb-8968-2bb9e0017d27.png)

2020-12-14 22:06 UTC, AngeloCG97 approved these changes

2020-12-14 22:08 UTC, JeanVegaD approved these changes

2020-12-14 23:01 UTC, JustinCast commented on webapp/src/components/MapPopup/index.js
> +import { makeStyles, ThemeProvider } from '@material-ui/styles'
Theme provider seems not to be used

2020-12-14 23:01 UTC, JustinCast commented on webapp/src/components/MapPopup/index.js
> +          {t('signup.address')}:{' '}
Curly braces here

2020-12-15 14:30 UTC, merged