fix(frontend): Sidebar menu elements
eoscostarica/lifebank pull request #504
Opened 2021-02-18 20:18 UTC by steph222

Resolves #311

2021-02-18 20:26 UTC, leisterfrancisco requested changes

2021-02-18 20:26 UTC, leisterfrancisco commented on webapp/src/language/en.json
>        "yourDonations": "Your Donations",
Your **D**onations == Tus **d**onaciones

_Capital letter_

2021-02-18 21:47 UTC, leisterfrancisco approved these changes
Good work 👍

2021-02-18 22:25 UTC, xavier506 commented
please see code factor comments

2021-02-22 21:04 UTC, Edgar097 approved these changes

2021-02-23 22:32 UTC, merged