Fix(frontend): Error 404 page
eoscostarica/lifebank pull request #513
Opened 2021-02-25 23:55 UTC by steph222

Resolves #495

2021-02-26 00:56 UTC, Edgar097 approved these changes

2021-03-10 22:42 UTC, tetogomez requested changes
Please check the comment

2021-03-10 22:42 UTC, tetogomez commented on webapp/src/routes/NotFound/NotFound.js
> +
unnecessary blank space

2021-03-12 21:43 UTC, steph222 commented on webapp/src/routes/NotFound/NotFound.js
> +
Thanks!!😊

2021-03-16 20:28 UTC, merged