fix(update data)
eoscostarica/lifebank pull request #632
Opened 2021-03-31 23:06 UTC by Edgar097

Resolves #562 

### What does this PR do?
Little description about the purpose

### How should this be tested?
- Make run
- Step 2
- Step 3

2021-04-06 15:40 UTC, leisterfrancisco commented
@Edgar097 what does this PR do?

2021-04-08 15:59 UTC, steph222 approved these changes

2021-04-08 17:28 UTC, JustinCast requested changes

2021-04-08 17:28 UTC, JustinCast commented on webapp/src/routes/Profile/ProfilePageLifebank.js
> +<<<<<<< HEAD
Hey @Edgar097 take a look at this

2021-04-08 19:34 UTC, Edgar097 commented
The offer loading data issue is solved in this PR, however the problem in the edition of the profiles still present, we hope we can solve this problem in future issues

2021-04-08 22:45 UTC, JustinCast approved these changes

2021-04-08 22:47 UTC, Edgar097 commented
Last commit, fix the donations

2021-04-08 22:50 UTC, JustinCast commented on webapp/src/components/Signup/Signup.js
> +      setErrorMessage(t('errors.authError'))
Why you added these curly braces?

2021-04-12 09:45 UTC, leisterfrancisco approved these changes

2021-04-12 09:45 UTC, merged