fix(logout button)
eoscostarica/lifebank pull request #641
Opened 2021-04-06 20:49 UTC by Edgar097

Resolves #620 

### What does this PR do?
Log out is a button now

### How should this be tested?
- Make run
- Log In
- Log Out

2021-04-06 23:07 UTC, steph222 approved these changes

2021-04-07 17:26 UTC, leisterfrancisco requested changes

2021-04-07 17:26 UTC, leisterfrancisco commented on webapp/src/containers/SideBar.js
>              </Typography>
Please add indentation

2021-04-08 16:25 UTC, leisterfrancisco approved these changes

2021-04-08 16:25 UTC, merged