Fix/credentials
eoscostarica/lifebank pull request #651
Opened 2021-04-12 16:07 UTC by Edgar097

Resolves #623 

### What does this PR do?
Credentials Recovery segmentation, password recovery

### How should this be tested?
- Make run
- Go to Login
- Recover the password

2021-04-12 16:29 UTC, JustinCast commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +
Delete this blank space

2021-04-12 21:11 UTC, JustinCast reviewed
Take a look at the conflicts!

2021-04-12 21:11 UTC, JustinCast commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +
Delete blank space here

2021-04-13 13:45 UTC, leisterfrancisco requested changes
I think there is too much space at the bottom, we can move the recover button a little bit lower

![image](https://user-images.githubusercontent.com/28828796/114562269-95760a80-9c2b-11eb-9b37-d4c6d8fe1e7b.png)

2021-04-13 13:48 UTC, leisterfrancisco requested changes
@Edgar097 take a look at this warning please
`Check warning on line 113 in webapp/src/components/CredentialsRecovery/CredentialsRecovery.js`

And also 
![image](https://user-images.githubusercontent.com/28828796/114563371-965b6c00-9c2c-11eb-82ff-585c0b5b8890.png)

Both of them are in CredentialsRecovery.js

2021-04-13 19:20 UTC, JustinCast approved these changes

2021-04-14 12:23 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +  }, [error,t])
add space after comma

2021-04-14 12:23 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +  }, [errorChangePassword,t])
add space after comma

2021-04-14 12:23 UTC, leisterfrancisco requested changes
Minor changes

2021-04-14 22:32 UTC, steph222 approved these changes

2021-04-16 15:23 UTC, leisterfrancisco requested changes
Minor changes

2021-04-16 15:23 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +
Leave the line break but remove the black space

2021-04-16 15:23 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +  recoveryBox: {
Remove empty space at the end

2021-04-19 10:17 UTC, leisterfrancisco requested changes
Minor indentations errors

2021-04-19 10:17 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
>                  {loading && <CircularProgress />}
Make indentation

2021-04-19 10:17 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
>                  <Alert
Make indentation

2021-04-19 10:17 UTC, leisterfrancisco commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
>                  <Alert
Make indentation

2021-04-19 10:17 UTC, leisterfrancisco commented
@Edgar097 take a look at merge conflicts

2021-04-19 19:48 UTC, steph222 commented
> @Edgar097 take a look at merge conflicts

@Edgar097  Look this

2021-04-19 20:42 UTC, Edgar097 commented
> > @Edgar097 take a look at merge conflicts
> 
> @Edgar097 Look this

@leisterfrancisco @steph222 can you check if it is working please

2021-04-19 22:18 UTC, leisterfrancisco commented
> > > @Edgar097 take a look at merge conflicts
> > 
> > 
> > @Edgar097 Look this
> 
> @leisterfrancisco @steph222 can you check if it is working please

@Edgar097 is working perfectly, check your local changes

2021-04-19 22:55 UTC, leisterfrancisco approved these changes

2021-04-19 22:56 UTC, merged