fix(email bug): remove email from memory
eoscostarica/lifebank pull request #657
Opened 2021-04-13 20:12 UTC by Edgar097

Resolves #598 

### What does this PR do?
Removes email data from memory

### How should this be tested?
- Make run
- Register a new user
- Try to register a new user with the same email

2021-04-13 21:26 UTC, JustinCast approved these changes

2021-04-14 12:24 UTC, leisterfrancisco requested changes

2021-04-14 12:24 UTC, leisterfrancisco commented on webapp/src/components/Signup/Signup.js
> +    },[open])
add space after comma

2021-04-14 22:31 UTC, steph222 approved these changes

2021-04-16 15:24 UTC, merged