Fix/offer button
eoscostarica/lifebank pull request #667
Opened 2021-04-14 17:49 UTC by Edgar097

Resolves #602 

### What does this PR do?
When clicking the add offer, if the profile is not complete, add a restriction until the data is enter

### How should this be tested?
- Make run
- Login as Sponsor
- Add an offer

2021-04-14 19:13 UTC, JustinCast requested changes

2021-04-14 19:13 UTC, JustinCast commented on webapp/src/components/Signup/Signup.js
> +      handleSetField('email', ' ')
Why an empty string?.

2021-04-14 19:13 UTC, JustinCast commented on webapp/src/language/en.json
> +      "info": "In order for you to add an Offer, please finish your profile information"
please ~finish~ complete your profile information?

2021-04-14 19:13 UTC, JustinCast commented on webapp/src/language/es.json
> +      "info": "Para que pueda agregar una Oferta, complete la información de su perfil"
Why "Oferta" is in capital case?

2021-04-14 19:13 UTC, JustinCast commented on webapp/src/routes/OffersManagement/OffersManagement.js
> +        onClick={() => checkAvailableFields()}
`onClick={checkAvailableFields}`

2021-04-15 16:58 UTC, JustinCast approved these changes

2021-04-15 17:00 UTC, JustinCast approved these changes

2021-04-16 15:12 UTC, steph222 approved these changes

2021-04-16 15:33 UTC, leisterfrancisco requested changes
Looks great to me, but what if we change the box message color to yellow? to try to represent a kind of a warning alert?

2021-04-16 15:33 UTC, leisterfrancisco commented on webapp/src/routes/OffersManagement/OffersManagement.js
> +    if(Object.keys(pendingFieldsObject).length>0){
Add space before and after the `>` symbol

2021-04-19 10:21 UTC, leisterfrancisco approved these changes

2021-04-19 10:21 UTC, merged