Fix/minorchanges offerts
eoscostarica/lifebank pull request #668
Opened 2021-04-14 22:15 UTC by steph222

Resolves #381 

### What does this PR do?
Fixes in the design of Offers Approval in Lifebanks and Offers Management in Sponsors

### How should this be tested?
- Make run
- Go to Offers Management
- Go to Offers Approval

2021-04-15 15:36 UTC, Edgar097 approved these changes

2021-04-16 15:20 UTC, leisterfrancisco requested changes
Try to go under **Offers Approval** under lifebank role without having accepted the consent contract, the app crash

2021-04-16 15:20 UTC, leisterfrancisco commented on webapp/src/language/en.json
> +      "availableOffers": "Approved Offers",
"availableOffers": "Approved Offers" - **Capital case**
"availableOffers": "Ofertas aprobadas" - **No Capital case**

2021-04-19 10:14 UTC, leisterfrancisco requested changes
The error still persist, 
> Try to go under Offers Approval under lifebank role without having accepted the consent contract, the app crash

![image](https://user-images.githubusercontent.com/28828796/115220195-7eb93300-a0c5-11eb-9820-5a679dea8131.png)

2021-04-21 14:42 UTC, leisterfrancisco approved these changes

2021-04-21 14:42 UTC, merged