feat(backend): add send email action
eoscostarica/lifebank pull request #672
Opened 2021-04-15 18:16 UTC by leisterfrancisco

Resolves #573 

### What does this PR do?
Enable the send email again option if user have not received email verification yet

### How should this be tested?
- Make run
- Login without having verified the email
- Check email is send

2021-04-23 09:43 UTC, leisterfrancisco reviewed
@steph222
1. What if we add a Snackbar when the user click the RESEND button
2. After user click RESEND button, modals close, that's right, but if a click login again, it will show up resend email modal again, take a look at that

2021-04-26 15:29 UTC, Edgar097 commented
I am not receiving the verification email with my hotmail account, and i have this current problem when trying to log in 
![image](https://user-images.githubusercontent.com/76976401/116109206-cfa2cb80-a671-11eb-926f-bf911acf4e59.png)

2021-04-26 15:35 UTC, Edgar097 reviewed
look at the comments @leisterfrancisco @steph222

2021-04-26 15:45 UTC, JustinCast requested changes
@leisterfrancisco great job. Just added a few things we can improve

2021-04-26 15:45 UTC, JustinCast commented on webapp/src/components/ResendComponent/ResendComponent.js
> +
Delete this blank space

2021-04-26 15:45 UTC, JustinCast commented on webapp/src/components/ResendComponent/ResendComponent.js
> +      aria-describedby="transition-modal-description"
These attributes seem to have their original placeholder

2021-04-26 15:45 UTC, JustinCast commented on webapp/src/components/LoginModal/Login.js
> +
Delete this blank space

2021-04-26 15:45 UTC, JustinCast commented on webapp/src/components/LoginModal/Login.js
> +
Delete this blank space

2021-04-26 15:45 UTC, JustinCast commented on webapp/src/components/LoginModal/Login.js
> +    console.log('SEND-EMAIL-RESULT', sendEmailResult)
Remove this console.log

2021-04-26 21:08 UTC, JustinCast approved these changes
LGTM

2021-04-27 15:02 UTC, merged