feat(frontend): add jspdf-react library
eoscostarica/lifebank pull request #689
Opened 2021-04-21 18:12 UTC by leisterfrancisco

Resolves #655 

### What does this PR do?
Enable the user to create a pdf or xml tokens transaction report

### How should this be tested?
- Make run
- Pending

2021-04-28 19:49 UTC, leisterfrancisco commented on hapi/src/api/account.api.js
> -const verifyEmailHandler = require('../routes/verify-email/verify-email.handler')
unused variable

2021-05-05 17:54 UTC, Edgar097 approved these changes
Looks really nice!

2021-05-05 18:00 UTC, JustinCast requested changes

2021-05-05 18:00 UTC, JustinCast commented on webapp/src/language/en.json
> +      "pdfFooter": "Lifebank is an open-source platform that uses blockchain technology to incentivizeblood donations. For more information about Lifebank, go to http://lifebank.io/.",
fix "incentivizeblood"

2021-05-05 18:00 UTC, JustinCast commented on webapp/src/language/es.json
> +      "pdfFooter": "Lifebank es una plataforma de código abierto que usa tecnología blockchain paraincentivar las donaciones de sangre. Para más información sobre Lifebank, visitehttp://lifebank.io/.
Fix "paraincentivar"

2021-05-05 20:05 UTC, JustinCast commented on webapp/src/components/TransactionReport/TransactionReport.js
> +    </>
Is this ok?

2021-05-05 20:15 UTC, JustinCast approved these changes

2021-05-05 22:08 UTC, steph222 approved these changes

2021-05-05 22:09 UTC, merged