Feat(frontend): add icons in offers
eoscostarica/lifebank pull request #712
Opened 2021-04-28 22:54 UTC by steph222

Resolves #605 

### What does this PR do?
A sponsor can choose among different icons to add to their offers

### How should this be tested?
- Make run
- Login as Sponsor 
- Add offer in Offers Management
- Check offers list

![image](https://user-images.githubusercontent.com/31549144/116482432-5f976f80-a842-11eb-84e5-58c065003785.png)

![image](https://user-images.githubusercontent.com/31549144/116482454-6b833180-a842-11eb-8e3d-dda9ce024781.png)

2021-04-28 23:01 UTC, JustinCast approved these changes
LGTM

2021-05-04 10:29 UTC, leisterfrancisco requested changes
@steph222 getting this error

![image](https://user-images.githubusercontent.com/28828796/116991029-31c28880-ac91-11eb-9ab6-e4bc332192d2.png)

2021-05-06 21:46 UTC, JustinCast commented on hasura/migrations/1620165951453_alter_table_public_offer_alter_column_icon/up.sql
> +ALTER TABLE "public"."offer" ALTER COLUMN "icon" DROP NOT NULL;
Too much migrations for such a small change

2021-05-06 21:46 UTC, JustinCast commented on webapp/src/routes/OffersManagement/GenericOfferFormComponent.js
> +
Delete this blank space

2021-05-07 16:12 UTC, leisterfrancisco requested changes
Still getting error
![image](https://user-images.githubusercontent.com/28828796/117478699-b96ff780-af1c-11eb-88ea-236a486d9b34.png)

2021-05-07 21:22 UTC, ldrojas commented
<img width="689" alt="Captura de Pantalla 2021-05-07 a la(s) 15 22 20" src="https://user-images.githubusercontent.com/29232417/117509755-074e2500-af48-11eb-9973-2e66f7c1480a.png">

2021-05-11 15:46 UTC, steph222 commented
> @steph222 Nice work, just one more thing, in home dir, in the offers section, one already created offer don't show any offer icon
> 
> ![image](https://user-images.githubusercontent.com/28828796/117810243-5d5aeb00-b21c-11eb-8a07-8cbf57673121.png)

This happens because the offer already existed in the database, so it will not show any icon until the offer is edited.
This is applied in this way so that the program has no problems

2021-05-12 15:37 UTC, JustinCast approved these changes

2021-05-12 18:16 UTC, leisterfrancisco requested changes
@steph222 still getting the non icon for an offer that already existed in the database

https://user-images.githubusercontent.com/28828796/117810243-5d5aeb00-b21c-11eb-8a07-8cbf57673121.png

2021-05-12 20:18 UTC, steph222 commented
> still getting the non icon for an offer that already existed in the database

There is already a default
![image](https://user-images.githubusercontent.com/31549144/118038903-f24d0980-b32c-11eb-8c6b-7f13ce7b924a.png)

2021-05-12 21:09 UTC, leisterfrancisco requested changes

2021-05-12 21:09 UTC, leisterfrancisco commented on hasura/migrations/1620148584870_alter_table_public_offer_add_column_icon/up.sql
> +ALTER TABLE "public"."offer" ADD COLUMN "icon" varchar NULL;
Please, set default value and remove null

2021-05-14 00:51 UTC, Edgar097 commented
Still getting the error if I dont set up the permissions, you should merge the changes too and check the conflicts.

2021-05-14 02:03 UTC, steph222 commented
> Still getting the error if I dont set up the permissions, you should merge the changes with the master too and check the conflicts.

Thanks!

2021-05-18 15:24 UTC, leisterfrancisco approved these changes

2021-05-18 15:24 UTC, merged