Fix(snackbar): add the same format for future implementation
eoscostarica/lifebank pull request #714
Opened 2021-04-30 18:30 UTC by Edgar097

Resolves #690 #636 #526

### What does this PR do?
Add the same implementation for all the snackbars in the app

### How should this be tested?
- Make run
- Navigate through the app
- Check if the snackbars work properly

2021-04-30 18:55 UTC, JustinCast requested changes

2021-04-30 18:55 UTC, JustinCast commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +      message: t('credentialsRecovery.passwordNotChangable'),
~passwordNotChangable~ passwordNotChangeable?

2021-04-30 18:55 UTC, JustinCast commented on webapp/src/components/CredentialsRecovery/CredentialsRecovery.js
> +      message: t('credentialsRecovery.passwordNotChangable'),
~passwordNotChangable~ passwordNotChangeable?

2021-04-30 18:55 UTC, JustinCast commented on webapp/src/components/DonationsDashboard/DonationsDashboard.js
> +
Delete this blank space

2021-04-30 18:55 UTC, JustinCast commented on webapp/src/components/DonationsDashboard/DonationsDashboard.js
> +import React, { useState, useEffect, forwardRef, useCallback } from 'react'
Are you using useCallback hook?

2021-04-30 18:55 UTC, JustinCast commented on webapp/src/components/LoginModal/Login.js
> +                  onClick={() => handleOpenAlert()}
onClick={handleOpenAlert}

2021-04-30 18:55 UTC, JustinCast commented
@Edgar097 take a look at Codefactor's warnings!

2021-04-30 22:26 UTC, JustinCast requested changes
@Edgar097 take a look at this 'setErrorMessage' is not defined. (no-undef) codefactor warning

2021-04-30 22:26 UTC, JustinCast commented
@Edgar097 also take a look at the conflicts

2021-04-30 22:39 UTC, JustinCast approved these changes

2021-05-04 10:24 UTC, leisterfrancisco approved these changes

2021-05-04 10:24 UTC, merged