feature(sponsor edit page): apply new design
eoscostarica/lifebank pull request #722
Opened 2021-05-06 19:51 UTC by Edgar097

Resolves #

### What does this PR do?
New sponsor edit page design

### How should this be tested?
- Make run
- Edit Sponsor

2021-05-10 18:30 UTC, leisterfrancisco requested changes
@Edgar097 please, take a look at title space consistency, seem not to have same margin for each title

![image](https://user-images.githubusercontent.com/28828796/117707136-66e84280-b18b-11eb-9cfd-d16f2ef51f64.png)

2021-05-11 12:00 UTC, leisterfrancisco commented
@Edgar097 check merge conflicts

2021-05-11 16:04 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfileSponsorMobile.js
> +                  socialMedia.find((social) => social.name === 'instagram')
Same situation here

2021-05-11 16:05 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfileSponsorMobile.js
> +                  socialMedia.find((social) => social.name === 'facebook')
Same situation here

2021-05-11 16:05 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfileSponsorMobile.js
> +                  socialMedia.find((social) => social.name === 'twitter')
Same situation here

2021-05-11 16:06 UTC, JustinCast commented on webapp/src/routes/EditProfile/EditProfileSponsorMobile.js
> +                onClick={() => prepareDataForSubmitting()}
`onClick={prepareDataForSubmitting}`

2021-05-11 16:07 UTC, JustinCast commented on webapp/src/routes/EditProfile/styles.js
> +    height: '287px'
Duplicate key height

2021-05-11 20:39 UTC, JustinCast approved these changes
👍

2021-05-11 23:21 UTC, steph222 approved these changes

2021-05-11 23:21 UTC, merged