Fix(frontend) negative numbers
eoscostarica/lifebank pull request #741
Opened 2021-05-13 23:04 UTC by steph222

Resolves #587 

### What does this PR do?
Eliminate the entry of negative numbers in the creation of offers

### How should this be tested?
- Make run
- Login as Sponsor 
- Go to Offers Management 
- Create offer

2021-05-14 00:39 UTC, Edgar097 approved these changes

2021-05-18 14:51 UTC, leisterfrancisco requested changes
Take a look at
![image](https://user-images.githubusercontent.com/28828796/118673410-379e8a80-b7b6-11eb-91d7-ae9eda2dda2c.png)

2021-05-18 15:24 UTC, steph222 commented
> Take a look at
> ![image](https://user-images.githubusercontent.com/28828796/118673410-379e8a80-b7b6-11eb-91d7-ae9eda2dda2c.png)

It is an external problem, not from my branch. Thanks for the observation

2021-05-18 16:57 UTC, leisterfrancisco approved these changes

2021-05-18 16:57 UTC, merged