Feat/settings
eoscostarica/lifebank pull request #747
Opened 2021-05-14 20:24 UTC by Edgar097

Resolves #624

### What does this PR do?
Settings Component @leisterfrancisco 

### How should this be tested?
- Make run
![image](https://user-images.githubusercontent.com/76976401/118324978-04ab7c80-b4c0-11eb-917b-e6dc40b823fe.png)

2021-05-27 17:12 UTC, leisterfrancisco requested changes
![image](https://user-images.githubusercontent.com/28828796/119868592-76ca8b00-bedc-11eb-8ae8-0966b4e7d442.png)

2021-05-31 18:01 UTC, Edgar097 commented
Check if everything is working properly please @leisterfrancisco @steph222

2021-05-31 19:05 UTC, leisterfrancisco requested changes
![image](https://user-images.githubusercontent.com/28828796/120232511-ef995200-c210-11eb-8f11-b3873e3af9bb.png)

2021-05-31 20:20 UTC, leisterfrancisco approved these changes

2021-05-31 20:57 UTC, steph222 approved these changes

2021-05-31 20:57 UTC, merged