fix(edit profile): bugs and map not showing
eoscostarica/lifebank pull request #772
Opened 2021-05-26 22:50 UTC by Edgar097

Resolves #765 

### What does this PR do?
Fix console errors and map not showing in sponsor and Lifebank

### How should this be tested?
- Make run
- Edit profile

2021-05-27 17:04 UTC, leisterfrancisco requested changes
Take a look at margins

![image](https://user-images.githubusercontent.com/28828796/119867634-53eba700-bedb-11eb-92a7-53386a662d3d.png)

2021-05-28 05:02 UTC, leisterfrancisco requested changes

2021-05-28 05:02 UTC, leisterfrancisco commented on hapi/src/api/user.api.js
> +  console.log(where, user)
Check this

2021-05-28 05:02 UTC, leisterfrancisco commented on hapi/src/api/user.api.js
> +  console.log(where, user)
Check this

2021-05-28 05:02 UTC, leisterfrancisco commented on hapi/src/api/user.api.js
> +  console.log(where, user)
Check this

2021-05-28 05:02 UTC, leisterfrancisco commented on hapi/src/api/user.api.js
> +  console.log(where, user)
Check this

2021-05-28 05:02 UTC, leisterfrancisco commented on hapi/src/api/user.api.js
> +  console.log(where)
Check this

2021-05-28 05:02 UTC, leisterfrancisco commented on webapp/src/routes/EditProfile/EditProfileBank.js
> +        console.log(userToSubmit)
Check this

2021-05-31 03:05 UTC, leisterfrancisco requested changes

2021-05-31 03:05 UTC, leisterfrancisco commented on hapi/src/api/user.api.js
> +  console.log(where)
Remove console log

2021-05-31 03:05 UTC, leisterfrancisco commented on webapp/src/routes/EditProfile/EditProfileSponsorMobile.js
> +                        aria-label="add photo url"
What if we add this to translation

2021-05-31 18:37 UTC, leisterfrancisco approved these changes

2021-05-31 20:33 UTC, steph222 approved these changes

2021-05-31 20:34 UTC, merged