feat(frontend): add hasura mutation to change email subscription flag
eoscostarica/lifebank pull request #777
Opened 2021-05-31 03:50 UTC by leisterfrancisco

Resolves #698 
Resolves #699  
Resolves #700 

### What does this PR do?
Add route to change email subscription

### How should this be tested?
- Make run
- Check emails inbox to try to disable email notifications
- Check in http://localhost:9695/console/data/schema/public/tables/user/browse that the user selected don't have email_subscription flag set to true

2021-05-31 17:53 UTC, Edgar097 commented
If i'm not log in an I type http://localhost:3000/cancel-email-subscription/:account it let me unsuscribe, i get a error snackbar and then the page location change to. 
![image](https://user-images.githubusercontent.com/76976401/120227334-3170cb00-c206-11eb-953a-804ea0278832.png)

Just for you to know
Also the email subscription is not changing at least for donors getting the same snackbar error
![image](https://user-images.githubusercontent.com/76976401/120227656-cbd10e80-c206-11eb-8c6e-4a3a90896505.png)

2021-06-01 17:17 UTC, Edgar097 requested changes
Email subscription flag not changing in the database

2021-06-01 18:03 UTC, leisterfrancisco commented
> Email subscription flag not changing in the database

@Edgar097 your fail case is working perfectly to me, did you rerun the project with `make run`

2021-06-02 15:48 UTC, steph222 approved these changes

2021-06-02 15:48 UTC, merged