Fix/change edit profile route
eoscostarica/lifebank pull request #792
Opened 2021-06-02 23:54 UTC by Edgar097

Resolves #735 

### What does this PR do?
Change Edit profile Route

### How should this be tested?
- Make run
- Go to edit profile with the sidebar

2021-06-05 02:25 UTC, leisterfrancisco requested changes

2021-06-05 02:25 UTC, leisterfrancisco commented on hapi/src/api/account.api.js
> +
remove black space

2021-06-07 15:40 UTC, steph222 requested changes
Please check merge conflicts

2021-06-07 16:39 UTC, steph222 approved these changes

2021-06-07 17:11 UTC, leisterfrancisco requested changes
I got this error:

<img width="862" alt="Screen Shot 2021-06-07 at 11 10 19" src="https://user-images.githubusercontent.com/28828796/121061448-17446900-c781-11eb-8003-491888566334.png">

2021-06-07 18:38 UTC, leisterfrancisco approved these changes

2021-06-07 18:39 UTC, merged